services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ub-app
    volumes:
      - .:/app
    command: python main.py
    depends_on:
      - redis
      - postgres
    environment: &common-env
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - POSTGRES_HOST=postgres

  celery: &celery-base
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    environment: *common-env

  celery_worker:
    <<: *celery-base
    container_name: ub-celery
    command: celery -A app.tasks.celery_app worker --loglevel=info

  celery_beat:
    <<: *celery-base
    container_name: ub-celery-beat
    command: celery -A app.tasks.celery_app beat --loglevel=info

  celery_flower:
    image: mher/flower
    container_name: ub-celery-flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - postgres
    environment: *common-env

  redis:
    image: redis:6.2
    container_name: ub-redis
    volumes:
      - ub-redis:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  postgres:
    image: postgres:12
    container_name: ub-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ub-postgres:/var/lib/postgresql/data

volumes:
  ub-redis:
  ub-postgres:
