x-app-base: &app-base
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/app
  depends_on:
    - redis
    - postgres
  environment: &common-env
    - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    - POSTGRES_HOST=postgres
  restart: unless-stopped

services:
  app:
    <<: *app-base
    container_name: ub-app
    command: python main.py

  celery_worker:
    <<: *app-base
    container_name: ub-celery
    command: celery -A app.tasks.celery_app worker --loglevel=info
    restart: unless-stopped

  celery_beat:
    <<: *app-base
    container_name: ub-celery-beat
    command: celery -A app.tasks.celery_app beat --loglevel=info
    restart: unless-stopped

  celery_flower:
    image: mher/flower
    container_name: ub-celery-flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - postgres
    environment: *common-env
    restart: unless-stopped

  redis:
    image: redis:6.2
    container_name: ub-redis
    volumes:
      - ub-redis:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: ub-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ub-postgres:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  ub-redis:
  ub-postgres:
